# Generated by Django 6.0 on 2025-12-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='adds/'),
        ),
    ]
