# Generated by Django 6.0 on 2025-12-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_add_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
