# Generated by Django 6.0 on 2025-12-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='image',
            field=models.ImageField(upload_to='adds/'),
        ),
        migrations.AlterField(
            model_name='add',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
