# Generated by Django 6.0 on 2025-12-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_add_image_alter_add_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
