# Generated by Django 6.0 on 2025-12-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_parent_alter_add_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
